const books = [
      {
        "id": "978-0141439518",
        "isbn": "0141439513",
        "title": "Pride and Prejudice",
        "author": "Jane Austen",
        "publisher": "Penguin Classics",
        "publicationYear": 2002,
        "genre": ["Fiction", "Romance", "Classic"],
        "location": "Fiction-A12",
        "status": "available",
        "totalCopies": 3,
        "availableCopies": 2,
        "language": "English",
        "format": "Paperback",
        "pages": 432,
        "description": "A classic tale of love and marriage in Georgian England",
        "lastBorrowed": "2024-02-15",
        "condition": "good"
      },
      {
        "id": "978-0062315007",
        "isbn": "0062315005",
        "title": "The Alchemist",
        "author": "Paulo Coelho",
        "publisher": "HarperOne",
        "publicationYear": 2014,
        "genre": ["Fiction", "Philosophy", "Adventure"],
        "location": "Fiction-C15",
        "status": "checked-out",
        "totalCopies": 2,
        "availableCopies": 0,
        "language": "English",
        "format": "Hardcover",
        "pages": 208,
        "description": "A mystical story about following one's dreams",
        "lastBorrowed": "2024-03-01",
        "condition": "excellent"
      },
      {
        "id": "978-0547928227",
        "isbn": "0547928220",
        "title": "The Hobbit",
        "author": "J.R.R. Tolkien",
        "publisher": "Houghton Mifflin",
        "publicationYear": 2012,
        "genre": ["Fiction", "Fantasy", "Adventure"],
        "location": "Fantasy-T20",
        "status": "available",
        "totalCopies": 4,
        "availableCopies": 3,
        "language": "English",
        "format": "Paperback",
        "pages": 368,
        "description": "A fantasy novel about Bilbo Baggins' journey",
        "lastBorrowed": "2024-01-20",
        "condition": "fair"
      },
      {
        "id": "978-0307474278",
        "isbn": "0307474275",
        "title": "The Da Vinci Code",
        "author": "Dan Brown",
        "publisher": "Anchor",
        "publicationYear": 2009,
        "genre": ["Fiction", "Thriller", "Mystery"],
        "location": "Mystery-B08",
        "status": "under-repair",
        "totalCopies": 2,
        "availableCopies": 0,
        "language": "English",
        "format": "Mass Market Paperback",
        "pages": 597,
        "description": "A mystery thriller involving ancient conspiracies",
        "lastBorrowed": "2024-02-28",
        "condition": "poor"
      },
      {
        "id": "978-1451673319",
        "isbn": "1451673310",
        "title": "Fahrenheit 451",
        "author": "Ray Bradbury",
        "publisher": "Simon & Schuster",
        "publicationYear": 2012,
        "genre": ["Fiction", "Science Fiction", "Dystopian"],
        "location": "SciFi-B15",
        "status": "available",
        "totalCopies": 3,
        "availableCopies": 3,
        "language": "English",
        "format": "Paperback",
        "pages": 249,
        "description": "A dystopian novel about a future society where books are banned",
        "lastBorrowed": "2024-01-05",
        "condition": "good"
      }
    ]
    export default books